/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardMyPackagesRouteImport } from './routes/dashboard/my-packages'
import { Route as DashboardReleaseRouteImport } from './routes/dashboard/release'
import { Route as PublicDocsIndexRouteImport } from './routes/_public/docs/index'
import { Route as PublicDocsPackageRouteImport } from './routes/_public/docs/$package'
import { Route as PublicPackagesIndexRouteImport } from './routes/_public/packages/index'
import { Route as PublicPackagesNameRouteImport } from './routes/_public/packages/$name'
import { Route as PublicPublishersNameRouteImport } from './routes/_public/publishers/$name'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyPackagesRoute = DashboardMyPackagesRouteImport.update({
  id: '/my-packages',
  path: '/my-packages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReleaseRoute = DashboardReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicDocsIndexRoute = PublicDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsPackageRoute = PublicDocsPackageRouteImport.update({
  id: '/docs/$package',
  path: '/docs/$package',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPackagesIndexRoute = PublicPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPackagesNameRoute = PublicPackagesNameRouteImport.update({
  id: '/packages/$name',
  path: '/packages/$name',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPublishersNameRoute = PublicPublishersNameRouteImport.update({
  id: '/publishers/$name',
  path: '/publishers/$name',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/my-packages': typeof DashboardMyPackagesRoute
  '/dashboard/release': typeof DashboardReleaseRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/$package': typeof PublicDocsPackageRoute
  '/packages/$name': typeof PublicPackagesNameRoute
  '/publishers/$name': typeof PublicPublishersNameRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/docs/': typeof PublicDocsIndexRoute
  '/packages/': typeof PublicPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/my-packages': typeof DashboardMyPackagesRoute
  '/dashboard/release': typeof DashboardReleaseRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs/$package': typeof PublicDocsPackageRoute
  '/packages/$name': typeof PublicPackagesNameRoute
  '/publishers/$name': typeof PublicPublishersNameRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/docs': typeof PublicDocsIndexRoute
  '/packages': typeof PublicPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/my-packages': typeof DashboardMyPackagesRoute
  '/dashboard/release': typeof DashboardReleaseRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/docs/$package': typeof PublicDocsPackageRoute
  '/_public/packages/$name': typeof PublicPackagesNameRoute
  '/_public/publishers/$name': typeof PublicPublishersNameRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/_public/docs/': typeof PublicDocsIndexRoute
  '/_public/packages/': typeof PublicPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/api/health'
    | '/dashboard/my-packages'
    | '/dashboard/release'
    | '/dashboard/'
    | '/docs/$package'
    | '/packages/$name'
    | '/publishers/$name'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/docs/'
    | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/api/health'
    | '/dashboard/my-packages'
    | '/dashboard/release'
    | '/'
    | '/dashboard'
    | '/docs/$package'
    | '/packages/$name'
    | '/publishers/$name'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/docs'
    | '/packages'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/api/$'
    | '/api/health'
    | '/dashboard/my-packages'
    | '/dashboard/release'
    | '/_public/'
    | '/dashboard/'
    | '/_public/docs/$package'
    | '/_public/packages/$name'
    | '/_public/publishers/$name'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/_public/docs/'
    | '/_public/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-packages': {
      id: '/dashboard/my-packages'
      path: '/my-packages'
      fullPath: '/dashboard/my-packages'
      preLoaderRoute: typeof DashboardMyPackagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/release': {
      id: '/dashboard/release'
      path: '/release'
      fullPath: '/dashboard/release'
      preLoaderRoute: typeof DashboardReleaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/docs/': {
      id: '/_public/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof PublicDocsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/$package': {
      id: '/_public/docs/$package'
      path: '/docs/$package'
      fullPath: '/docs/$package'
      preLoaderRoute: typeof PublicDocsPackageRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/packages/': {
      id: '/_public/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PublicPackagesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/packages/$name': {
      id: '/_public/packages/$name'
      path: '/packages/$name'
      fullPath: '/packages/$name'
      preLoaderRoute: typeof PublicPackagesNameRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/publishers/$name': {
      id: '/_public/publishers/$name'
      path: '/publishers/$name'
      fullPath: '/publishers/$name'
      preLoaderRoute: typeof PublicPublishersNameRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDocsPackageRoute: typeof PublicDocsPackageRoute
  PublicPackagesNameRoute: typeof PublicPackagesNameRoute
  PublicPublishersNameRoute: typeof PublicPublishersNameRoute
  PublicDocsIndexRoute: typeof PublicDocsIndexRoute
  PublicPackagesIndexRoute: typeof PublicPackagesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicDocsPackageRoute: PublicDocsPackageRoute,
  PublicPackagesNameRoute: PublicPackagesNameRoute,
  PublicPublishersNameRoute: PublicPublishersNameRoute,
  PublicDocsIndexRoute: PublicDocsIndexRoute,
  PublicPackagesIndexRoute: PublicPackagesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardMyPackagesRoute: typeof DashboardMyPackagesRoute
  DashboardReleaseRoute: typeof DashboardReleaseRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMyPackagesRoute: DashboardMyPackagesRoute,
  DashboardReleaseRoute: DashboardReleaseRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
