packages:
  - beskid_tracker
  - beskid_web_common
  - beskid_web_common/packages/*
  - pckg/web
  - site/auth
  - site/website
  - site/learn

allowBuilds:
  '@biomejs/biome': set this to true or false
  '@fission-ai/openspec': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false

catalogs:
  tanstack-start:
    '@tanstack/react-devtools': 0.10.9
    '@tanstack/react-router': 1.170.28
    '@tanstack/react-start': 1.168.45
    '@tanstack/react-router-devtools': 1.167.1
