use crate::model::{InteropDecl, ReturnGroup};
use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

pub fn generate_stdinterop_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");
    output.push_str("enum StdInterop {\n");
    for decl in decls {
        output.push_str("    ");
        output.push_str(&decl.variant_name);
        output.push('(');
        for (index, param) in decl.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&param.beskid_type);
            output.push(' ');
            output.push_str(&param.name);
        }
        output.push_str("),\n");
    }
    output.push_str("}\n");
    output
}

pub fn generate_calls_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");
    output.push_str("pub mod std {\n");

    let mut modules: BTreeMap<String, Vec<&InteropDecl>> = BTreeMap::new();
    for decl in decls {
        let module = decl
            .module_path
            .strip_prefix("std.")
            .unwrap_or("")
            .to_string();
        modules.entry(module).or_default().push(decl);
    }

    for (module_name, entries) in modules {
        output.push_str(&format!("    pub mod {} {{\n", module_name));
        for decl in entries {
            output.push_str(&format!(
                "        pub {} {}(",
                decl.return_group.beskid_return_type(),
                decl.function_name
            ));

            for (index, param) in decl.params.iter().enumerate() {
                if index > 0 {
                    output.push_str(", ");
                }
                output.push_str(&format!("{}: {}", param.name, param.beskid_type));
            }
            output.push_str(") {\n");

            let params = decl
                .params
                .iter()
                .map(|param| param.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");

            let ffi_builtin = format!("__{}", decl.runtime_symbol);
            if decl.return_group == ReturnGroup::Unit {
                output.push_str(&format!("            {}({});\n", ffi_builtin, params));
            } else {
                output.push_str(&format!("            return {}({});\n", ffi_builtin, params));
            }

            output.push_str("        }\n\n");
        }
        output.push_str("    }\n\n");
    }

    output.push_str("}\n");
    output
}

pub fn generate_prelude_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");

    output.push_str("enum StdInterop {\n");
    for decl in decls {
        output.push_str("    ");
        output.push_str(&decl.variant_name);
        output.push('(');
        for (index, param) in decl.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&param.beskid_type);
            output.push(' ');
            output.push_str(&param.name);
        }
        output.push_str("),\n");
    }
    output.push_str("}\n\n");

    output.push_str(&generate_calls_source(decls));
    output
}

pub fn generate_runtime_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");
    output.push_str("use beskid_abi::BeskidStr;\n\n");

    for (index, decl) in decls.iter().enumerate() {
        output.push_str(&format!(
            "pub const TAG_{}: i32 = {};\n",
            screaming_snake_case(&decl.variant_name),
            index
        ));
    }
    output.push('\n');

    output.push_str("pub unsafe fn dispatch_unit(tag: i32, enum_ptr: *const u8) -> bool {\n");
    output.push_str("    match tag {\n");
    for decl in decls
        .iter()
        .filter(|decl| decl.return_group == ReturnGroup::Unit)
    {
        output.push_str(&format!(
            "        TAG_{} => {{\n",
            screaming_snake_case(&decl.variant_name)
        ));
        output.push_str(&render_runtime_param_loads(decl));
        output.push_str(&format!(
            "            crate::builtins::{}({});\n",
            decl.runtime_symbol,
            render_runtime_param_names(decl)
        ));
        output.push_str("            true\n");
        output.push_str("        }\n");
    }
    output.push_str("        _ => false,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str(
        "pub unsafe fn dispatch_usize(tag: i32, enum_ptr: *const u8) -> Option<usize> {\n",
    );
    output.push_str("    match tag {\n");
    for decl in decls
        .iter()
        .filter(|decl| decl.return_group == ReturnGroup::Usize)
    {
        output.push_str(&format!(
            "        TAG_{} => {{\n",
            screaming_snake_case(&decl.variant_name)
        ));
        output.push_str(&render_runtime_param_loads(decl));
        output.push_str(&format!(
            "            Some(crate::builtins::{}({}))\n",
            decl.runtime_symbol,
            render_runtime_param_names(decl)
        ));
        output.push_str("        }\n");
    }
    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    let ptr_param_name = if decls.iter().any(|decl| decl.return_group == ReturnGroup::Ptr) {
        "enum_ptr"
    } else {
        "_enum_ptr"
    };
    output.push_str(&format!(
        "pub unsafe fn dispatch_ptr(tag: i32, {ptr_param_name}: *const u8) -> Option<*mut u8> {{\n"
    ));
    output.push_str("    match tag {\n");
    for decl in decls
        .iter()
        .filter(|decl| decl.return_group == ReturnGroup::Ptr)
    {
        output.push_str(&format!(
            "        TAG_{} => {{\n",
            screaming_snake_case(&decl.variant_name)
        ));
        output.push_str(&render_runtime_param_loads(decl));
        output.push_str(&format!(
            "            Some(crate::builtins::{}({}))\n",
            decl.runtime_symbol,
            render_runtime_param_names(decl)
        ));
        output.push_str("        }\n");
    }
    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    output
}

fn render_runtime_param_loads(decl: &InteropDecl) -> String {
    decl.params
        .iter()
        .enumerate()
        .map(|(index, param)| {
            let offset = 16 + (index * 8);
            format!(
                "            let {} = unsafe {{ *(enum_ptr.add({offset}) as *const {}) }};\n",
                param.name,
                runtime_rust_param_type(&param.beskid_type)
            )
        })
        .collect::<Vec<_>>()
        .join("")
}

fn render_runtime_param_names(decl: &InteropDecl) -> String {
    decl.params
        .iter()
        .map(|param| param.name.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn runtime_rust_param_type(beskid_type: &str) -> &'static str {
    match beskid_type {
        "string" => "*const BeskidStr",
        _ => "*const u8",
    }
}

fn screaming_snake_case(input: &str) -> String {
    let mut out = String::new();
    for (index, ch) in input.chars().enumerate() {
        if ch.is_uppercase() && index > 0 {
            out.push('_');
        }
        out.extend(ch.to_uppercase());
    }
    out
}

pub fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    let current = fs::read_to_string(path).ok();
    if current.as_deref() == Some(content) {
        return Ok(());
    }

    fs::write(path, content)
        .with_context(|| format!("write generated interop source `{}`", path.display()))?;
    Ok(())
}

pub fn check_generated_file(path: &Path, expected: &str) -> Result<()> {
    let current = fs::read_to_string(path)
        .with_context(|| format!("read generated file `{}`", path.display()))?;
    if current != expected {
        anyhow::bail!(
            "generated interop file is stale: `{}` (run `pekan_cli interop`)",
            path.display()
        );
    }
    Ok(())
}
