use anyhow::{Context, Result};
use clap::Args;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum ReturnGroup {
    Unit,
    Usize,
    Ptr,
}

fn generate_prelude_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");

    output.push_str("enum StdInterop {\n");
    for decl in decls {
        output.push_str("    ");
        output.push_str(&decl.variant_name);
        output.push('(');
        for (index, param) in decl.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&param.beskid_type);
            output.push(' ');
            output.push_str(&param.name);
        }
        output.push_str("),\n");
    }
    output.push_str("}\n\n");

    output.push_str(&generate_calls_source(decls));
    output
}

fn generate_runtime_tags_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");

    for (index, decl) in decls.iter().enumerate() {
        output.push_str(&format!(
            "pub const TAG_{}: i32 = {};\n",
            screaming_snake_case(&decl.variant_name),
            index
        ));
    }
    output
}

impl ReturnGroup {
    fn dispatch_builtin(self) -> &'static str {
        match self {
            ReturnGroup::Unit => "__interop_dispatch_unit",
            ReturnGroup::Usize => "__interop_dispatch_usize",
            ReturnGroup::Ptr => "__interop_dispatch_ptr",
        }
    }

    fn beskid_return_type(self) -> &'static str {
        match self {
            ReturnGroup::Unit => "unit",
            ReturnGroup::Usize => "i64",
            ReturnGroup::Ptr => "ptr",
        }
    }
}

#[derive(Debug, Clone)]
struct InteropParam {
    name: String,
    beskid_type: String,
}

#[derive(Debug, Clone)]
struct InteropDecl {
    module_path: String,
    function_name: String,
    variant_name: String,
    params: Vec<InteropParam>,
    return_group: ReturnGroup,
    source: PathBuf,
    line: usize,
}

#[derive(Args, Debug)]
pub struct InteropArgs {
    /// Root directory containing Rust interop declaration spec files
    #[arg(long, default_value = "crates/beskid_runtime/interop_spec")]
    pub spec_root: PathBuf,

    /// Output directory for generated Beskid interop source files
    #[arg(long, default_value = "standard_library/Src/Interop")]
    pub output_dir: PathBuf,

    /// Generated stdlib prelude entry file (kept in sync with generated interop files)
    #[arg(long, default_value = "standard_library/Src/Prelude.bd")]
    pub prelude_output: PathBuf,

    /// Generated runtime tag constants file for dispatch contract synchronization
    #[arg(long, default_value = "crates/beskid_runtime/src/interop_generated.rs")]
    pub runtime_output: PathBuf,

    /// Check mode: fail if generated files differ from current contents
    #[arg(long)]
    pub check: bool,

    /// Print what would be generated without writing files
    #[arg(long)]
    pub dry_run: bool,
}

pub fn execute(args: InteropArgs) -> Result<()> {
    let spec_files = collect_spec_files(&args.spec_root)?;
    let mut decls = Vec::new();
    for path in spec_files {
        decls.extend(parse_spec_file(&path)?);
    }

    if decls.is_empty() {
        anyhow::bail!(
            "no #[InteropCall(...)] declarations found under `{}`",
            args.spec_root.display()
        );
    }

    decls.sort_by(|left, right| {
        left.module_path
            .cmp(&right.module_path)
            .then(left.function_name.cmp(&right.function_name))
            .then(left.variant_name.cmp(&right.variant_name))
    });
    validate_declarations(&decls)?;

    let enum_source = generate_stdinterop_source(&decls);
    let calls_source = generate_calls_source(&decls);
    let prelude_source = generate_prelude_source(&decls);
    let runtime_source = generate_runtime_tags_source(&decls);

    let enum_path = args.output_dir.join("StdInterop.generated.bd");
    let calls_path = args.output_dir.join("Calls.generated.bd");
    let prelude_path = args.prelude_output;
    let runtime_path = args.runtime_output;

    if args.dry_run {
        println!("Would generate:");
        println!("  {}", enum_path.display());
        println!("  {}", calls_path.display());
        println!("  {}", prelude_path.display());
        println!("  {}", runtime_path.display());
        return Ok(());
    }

    if args.check {
        check_generated_file(&enum_path, &enum_source)?;
        check_generated_file(&calls_path, &calls_source)?;
        check_generated_file(&prelude_path, &prelude_source)?;
        check_generated_file(&runtime_path, &runtime_source)?;
        println!("Interop generated files are up to date.");
        return Ok(());
    }

    fs::create_dir_all(&args.output_dir)
        .with_context(|| format!("create output directory `{}`", args.output_dir.display()))?;

    if let Some(parent) = prelude_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create output directory `{}`", parent.display()))?;
    }
    if let Some(parent) = runtime_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create output directory `{}`", parent.display()))?;
    }

    write_if_changed(&enum_path, &enum_source)?;
    write_if_changed(&calls_path, &calls_source)?;
    write_if_changed(&prelude_path, &prelude_source)?;
    write_if_changed(&runtime_path, &runtime_source)?;

    println!("Generated interop source files:");
    println!("  {}", enum_path.display());
    println!("  {}", calls_path.display());
    println!("  {}", prelude_path.display());
    println!("  {}", runtime_path.display());
    Ok(())
}

fn collect_spec_files(root: &Path) -> Result<Vec<PathBuf>> {
    if !root.exists() {
        anyhow::bail!("interop spec root does not exist: `{}`", root.display());
    }
    let mut files = Vec::new();
    collect_spec_files_recursive(root, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_spec_files_recursive(root: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    for entry in
        fs::read_dir(root).with_context(|| format!("read directory `{}`", root.display()))?
    {
        let entry = entry.with_context(|| format!("read entry under `{}`", root.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_spec_files_recursive(&path, files)?;
            continue;
        }

        if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            files.push(path);
        }
    }
    Ok(())
}

fn parse_spec_file(path: &Path) -> Result<Vec<InteropDecl>> {
    let source = fs::read_to_string(path)
        .with_context(|| format!("read interop spec file `{}`", path.display()))?;

    let mut decls = Vec::new();
    let lines: Vec<&str> = source.lines().collect();
    let mut index = 0usize;
    while index < lines.len() {
        let line = lines[index].trim();
        if !line.starts_with("#[InteropCall(") {
            index += 1;
            continue;
        }

        let (module_path, explicit_name) = parse_interop_attr(line)
            .with_context(|| format!("{}:{}", path.display(), index + 1))?;
        index += 1;

        while index < lines.len() {
            let candidate = lines[index].trim();
            if candidate.is_empty() || candidate.starts_with("//") {
                index += 1;
                continue;
            }

            let (function_name, params, return_group) = parse_fn_signature(candidate)
                .with_context(|| format!("{}:{}", path.display(), index + 1))?;

            let function_name = explicit_name.unwrap_or(function_name);
            let variant_name = make_variant_name(&module_path, &function_name);
            decls.push(InteropDecl {
                module_path,
                function_name,
                variant_name,
                params,
                return_group,
                source: path.to_path_buf(),
                line: index + 1,
            });
            index += 1;
            break;
        }
    }

    Ok(decls)
}

fn parse_interop_attr(line: &str) -> Result<(String, Option<String>)> {
    if !line.ends_with(")]") {
        anyhow::bail!("expected closing )] in InteropCall attribute");
    }
    let inner = line
        .strip_prefix("#[InteropCall(")
        .and_then(|tail| tail.strip_suffix(")]"))
        .ok_or_else(|| anyhow::anyhow!("invalid InteropCall attribute syntax"))?
        .trim();

    let mut parts = inner.split(',').map(str::trim);
    let module_part = parts
        .next()
        .ok_or_else(|| anyhow::anyhow!("InteropCall requires module path"))?;
    let module_path = unquote(module_part)
        .ok_or_else(|| anyhow::anyhow!("InteropCall module path must be a string literal"))?;

    let mut explicit_name = None;
    for part in parts {
        if let Some(rest) = part.strip_prefix("name") {
            let value = rest
                .trim_start()
                .strip_prefix('=')
                .map(str::trim)
                .ok_or_else(|| anyhow::anyhow!("expected `name = \"...\"`"))?;
            explicit_name = Some(
                unquote(value)
                    .ok_or_else(|| anyhow::anyhow!("`name` must be a string literal"))?
                    .to_string(),
            );
            continue;
        }
        anyhow::bail!("unsupported InteropCall argument `{part}`");
    }

    Ok((module_path.to_string(), explicit_name))
}

fn parse_fn_signature(line: &str) -> Result<(String, Vec<InteropParam>, ReturnGroup)> {
    let fn_pos = line
        .find("fn ")
        .ok_or_else(|| anyhow::anyhow!("expected function declaration after InteropCall"))?;
    let tail = &line[fn_pos + 3..];

    let open = tail
        .find('(')
        .ok_or_else(|| anyhow::anyhow!("expected `(` in function signature"))?;
    let close = tail[open + 1..]
        .find(')')
        .map(|index| open + 1 + index)
        .ok_or_else(|| anyhow::anyhow!("expected `)` in function signature"))?;

    let name = tail[..open].trim();
    if name.is_empty() {
        anyhow::bail!("function name cannot be empty");
    }

    let params_raw = tail[open + 1..close].trim();
    let mut params = Vec::new();
    if !params_raw.is_empty() {
        for raw_param in params_raw.split(',') {
            let raw_param = raw_param.trim();
            let (param_name, rust_type) = raw_param
                .split_once(':')
                .ok_or_else(|| anyhow::anyhow!("expected parameter format `name: Type`"))?;
            let param_name = param_name.trim();
            let rust_type = rust_type.trim();
            if param_name.is_empty() {
                anyhow::bail!("parameter name cannot be empty");
            }
            let beskid_type = map_rust_param_type(rust_type)?;
            params.push(InteropParam {
                name: param_name.to_string(),
                beskid_type: beskid_type.to_string(),
            });
        }
    }

    let after_paren = tail[close + 1..].trim();
    let return_group = if let Some((_, rhs)) = after_paren.split_once("->") {
        let rhs = rhs.trim();
        let end = rhs.find(['{', ';']).unwrap_or(rhs.len());
        map_rust_return_type(rhs[..end].trim())?
    } else {
        ReturnGroup::Unit
    };

    Ok((name.to_string(), params, return_group))
}

fn map_rust_param_type(ty: &str) -> Result<&'static str> {
    match ty {
        "&str" | "String" | "*const BeskidStr" => Ok("string"),
        _ => anyhow::bail!("unsupported interop parameter type `{ty}`"),
    }
}

fn map_rust_return_type(ty: &str) -> Result<ReturnGroup> {
    match ty {
        "()" => Ok(ReturnGroup::Unit),
        "usize" => Ok(ReturnGroup::Usize),
        "*mut u8" => Ok(ReturnGroup::Ptr),
        _ => anyhow::bail!("unsupported interop return type `{ty}`"),
    }
}

fn validate_declarations(decls: &[InteropDecl]) -> Result<()> {
    let mut seen = BTreeSet::new();
    for decl in decls {
        if !decl.module_path.starts_with("std.") {
            anyhow::bail!(
                "{}:{} invalid module path `{}` (must start with `std.`)",
                decl.source.display(),
                decl.line,
                decl.module_path
            );
        }

        let key = format!("{}::{}", decl.module_path, decl.function_name);
        if !seen.insert(key.clone()) {
            anyhow::bail!(
                "duplicate interop declaration `{}` at {}:{}",
                key,
                decl.source.display(),
                decl.line
            );
        }
    }
    Ok(())
}

fn generate_stdinterop_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");
    output.push_str("enum StdInterop {\n");
    for decl in decls {
        output.push_str("    ");
        output.push_str(&decl.variant_name);
        output.push('(');
        for (index, param) in decl.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            output.push_str(&param.beskid_type);
            output.push(' ');
            output.push_str(&param.name);
        }
        output.push_str("),\n");
    }
    output.push_str("}\n");
    output
}

fn generate_calls_source(decls: &[InteropDecl]) -> String {
    let mut output = String::new();
    output.push_str("// GENERATED FILE - DO NOT EDIT.\n");
    output.push_str("// Generated by `pekan_cli interop`.\n\n");
    output.push_str("pub mod std {\n");

    let mut modules: BTreeMap<String, Vec<&InteropDecl>> = BTreeMap::new();
    for decl in decls {
        let module = decl
            .module_path
            .strip_prefix("std.")
            .unwrap_or("")
            .to_string();
        modules.entry(module).or_default().push(decl);
    }

    for (module_name, entries) in modules {
        output.push_str(&format!("    pub mod {} {{\n", module_name));
        for decl in entries {
            output.push_str(&format!(
                "        pub {} {}(",
                decl.return_group.beskid_return_type(),
                decl.function_name
            ));

            for (index, param) in decl.params.iter().enumerate() {
                if index > 0 {
                    output.push_str(", ");
                }
                output.push_str(&format!("{} {}", param.beskid_type, param.name));
            }
            output.push_str(") {\n");

            let params = decl
                .params
                .iter()
                .map(|param| param.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");

            if decl.return_group == ReturnGroup::Unit {
                output.push_str(&format!(
                    "            {}(StdInterop::{}({}));\n",
                    decl.return_group.dispatch_builtin(),
                    decl.variant_name,
                    params
                ));
            } else {
                output.push_str(&format!(
                    "            return {}(StdInterop::{}({}));\n",
                    decl.return_group.dispatch_builtin(),
                    decl.variant_name,
                    params
                ));
            }

            output.push_str("        }\n\n");
        }
        output.push_str("    }\n\n");
    }

    output.push_str("}\n");
    output
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    let current = fs::read_to_string(path).ok();
    if current.as_deref() == Some(content) {
        return Ok(());
    }

    fs::write(path, content)
        .with_context(|| format!("write generated interop source `{}`", path.display()))?;
    Ok(())
}

fn check_generated_file(path: &Path, expected: &str) -> Result<()> {
    let current = fs::read_to_string(path)
        .with_context(|| format!("read generated file `{}`", path.display()))?;
    if current != expected {
        anyhow::bail!(
            "generated interop file is stale: `{}` (run `pekan_cli interop`)",
            path.display()
        );
    }
    Ok(())
}

fn make_variant_name(module_path: &str, function_name: &str) -> String {
    let mut parts = module_path
        .split('.')
        .skip(1)
        .map(pascal_case)
        .collect::<Vec<_>>();
    parts.push(pascal_case(function_name));
    parts.join("")
}

fn pascal_case(input: &str) -> String {
    input
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    let mut out = String::new();
                    out.extend(first.to_uppercase());
                    out.push_str(chars.as_str());
                    out
                }
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("")
}

fn screaming_snake_case(input: &str) -> String {
    let mut out = String::new();
    for (index, ch) in input.chars().enumerate() {
        if ch.is_uppercase() && index > 0 {
            out.push('_');
        }
        out.extend(ch.to_uppercase());
    }
    out
}

fn unquote(value: &str) -> Option<&str> {
    value
        .strip_prefix('"')
        .and_then(|tail| tail.strip_suffix('"'))
}

#[cfg(test)]
mod tests {
    use super::{
        InteropDecl, InteropParam, ReturnGroup, check_generated_file, generate_calls_source,
        generate_prelude_source, generate_runtime_tags_source, generate_stdinterop_source,
        parse_fn_signature, parse_interop_attr,
    };
    use std::fs;
    use std::path::PathBuf;

    #[test]
    fn parse_interop_attr_supports_module_and_name_override() {
        let (module, name) = parse_interop_attr("#[InteropCall(\"std.io\", name = \"println\")]")
            .expect("attribute should parse");
        assert_eq!(module, "std.io");
        assert_eq!(name.as_deref(), Some("println"));
    }

    #[test]
    fn parse_fn_signature_maps_types() {
        let (name, params, group) = parse_fn_signature("fn len(text: *const BeskidStr) -> usize;")
            .expect("signature should parse");
        assert_eq!(name, "len");
        assert_eq!(group, ReturnGroup::Usize);
        assert_eq!(params.len(), 1);
        assert_eq!(params[0].name, "text");
        assert_eq!(params[0].beskid_type, "string");
    }

    #[test]
    fn generated_sources_are_deterministic_by_sorted_input() {
        let mut decls = vec![
            InteropDecl {
                module_path: "std.string".to_string(),
                function_name: "len".to_string(),
                variant_name: "StringLen".to_string(),
                params: vec![InteropParam {
                    name: "text".to_string(),
                    beskid_type: "string".to_string(),
                }],
                return_group: ReturnGroup::Usize,
                source: PathBuf::from("spec.rs"),
                line: 1,
            },
            InteropDecl {
                module_path: "std.io".to_string(),
                function_name: "println".to_string(),
                variant_name: "IoPrintln".to_string(),
                params: vec![InteropParam {
                    name: "text".to_string(),
                    beskid_type: "string".to_string(),
                }],
                return_group: ReturnGroup::Unit,
                source: PathBuf::from("spec.rs"),
                line: 2,
            },
        ];
        decls.sort_by(|left, right| {
            left.module_path
                .cmp(&right.module_path)
                .then(left.function_name.cmp(&right.function_name))
                .then(left.variant_name.cmp(&right.variant_name))
        });

        let enum_source = generate_stdinterop_source(&decls);
        let calls_source = generate_calls_source(&decls);
        let prelude_source = generate_prelude_source(&decls);
        let runtime_source = generate_runtime_tags_source(&decls);

        assert!(
            enum_source.contains("IoPrintln") && enum_source.contains("StringLen"),
            "expected both variants to be generated"
        );
        assert!(
            calls_source.contains("pub mod io") && calls_source.contains("pub mod string"),
            "expected module wrappers to be generated"
        );

        let io_index = enum_source
            .find("IoPrintln")
            .expect("expected IoPrintln variant");
        let string_index = enum_source
            .find("StringLen")
            .expect("expected StringLen variant");
        assert!(io_index < string_index, "expected sorted variant order");
        assert!(
            prelude_source.contains("enum StdInterop") && prelude_source.contains("pub mod std"),
            "expected generated prelude to contain enum and std wrappers"
        );
        assert!(
            runtime_source.contains("TAG_IO_PRINTLN") && runtime_source.contains("TAG_STRING_LEN"),
            "expected runtime tag constants to be generated"
        );
    }

    #[test]
    fn check_generated_file_reports_stale_output() {
        let path = std::env::temp_dir().join(format!(
            "interop_check_test_{}_{}.bd",
            std::process::id(),
            42
        ));
        fs::write(&path, "old").expect("write temp file");

        let err = check_generated_file(&path, "new").expect_err("expected stale mismatch");
        let message = err.to_string();
        assert!(message.contains("stale"), "expected stale file error message");

        let _ = fs::remove_file(path);
    }
}
