use anyhow::{Context, Result};
use clap::Args;
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Clone, Copy)]
struct InteropVariant {
    name: &'static str,
    param_type: &'static str,
    param_name: &'static str,
}

#[derive(Debug, Clone, Copy)]
struct InteropWrapper {
    module: &'static str,
    function_name: &'static str,
    return_type: &'static str,
    dispatch_function: &'static str,
    variant_name: &'static str,
    param_type: &'static str,
    param_name: &'static str,
}

const INTEROP_VARIANTS: &[InteropVariant] = &[
    InteropVariant {
        name: "IoPrint",
        param_type: "string",
        param_name: "text",
    },
    InteropVariant {
        name: "IoPrintln",
        param_type: "string",
        param_name: "text",
    },
    InteropVariant {
        name: "StringLen",
        param_type: "string",
        param_name: "text",
    },
];

const INTEROP_WRAPPERS: &[InteropWrapper] = &[
    InteropWrapper {
        module: "io",
        function_name: "print",
        return_type: "unit",
        dispatch_function: "__interop_dispatch_unit",
        variant_name: "IoPrint",
        param_type: "string",
        param_name: "text",
    },
    InteropWrapper {
        module: "io",
        function_name: "println",
        return_type: "unit",
        dispatch_function: "__interop_dispatch_unit",
        variant_name: "IoPrintln",
        param_type: "string",
        param_name: "text",
    },
    InteropWrapper {
        module: "string",
        function_name: "len",
        return_type: "i64",
        dispatch_function: "__interop_dispatch_usize",
        variant_name: "StringLen",
        param_type: "string",
        param_name: "text",
    },
];

#[derive(Args, Debug)]
pub struct InteropArgs {
    /// Output path for generated interop Beskid source
    #[arg(long, default_value = "standard_library/Src/Interop.generated.bd")]
    pub output: PathBuf,
}

pub fn execute(args: InteropArgs) -> Result<()> {
    if let Some(parent) = args.output.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create output directory `{}`", parent.display()))?;
    }

    let generated = generate_interop_source();
    fs::write(&args.output, generated)
        .with_context(|| format!("write generated interop source `{}`", args.output.display()))?;

    println!("Generated interop source at {}", args.output.display());
    Ok(())
}

fn generate_interop_source() -> String {
    let mut output = String::new();
    output.push_str("// Auto-generated by `beskid interop`.\n");
    output.push_str("// Initial stdlib seeding is intentionally manual.\n\n");

    output.push_str("enum StdInterop {\n");
    for variant in INTEROP_VARIANTS {
        output.push_str(&format!(
            "    {}({} {}),\n",
            variant.name, variant.param_type, variant.param_name
        ));
    }
    output.push_str("}\n\n");

    output.push_str("pub mod std {\n");

    let mut modules: BTreeMap<&str, Vec<&InteropWrapper>> = BTreeMap::new();
    for wrapper in INTEROP_WRAPPERS {
        modules.entry(wrapper.module).or_default().push(wrapper);
    }

    for (module_name, wrappers) in modules {
        output.push_str(&format!("    pub mod {} {{\n", module_name));
        for wrapper in wrappers {
            output.push_str(&format!(
                "        pub {} {}({} {}) {{\n",
                wrapper.return_type, wrapper.function_name, wrapper.param_type, wrapper.param_name
            ));
            if wrapper.return_type == "unit" {
                output.push_str(&format!(
                    "            {}(StdInterop::{}({}));\n",
                    wrapper.dispatch_function, wrapper.variant_name, wrapper.param_name
                ));
            } else {
                output.push_str(&format!(
                    "            return {}(StdInterop::{}({}));\n",
                    wrapper.dispatch_function, wrapper.variant_name, wrapper.param_name
                ));
            }
            output.push_str("        }\n\n");
        }
        output.push_str("    }\n\n");
    }

    output.push_str("}\n");
    output
}
