#!/usr/bin/env bash
# Install vendored arcusis/coolify for OpenTofu (filesystem mirror; not on registry).
# Skips go build when the binary is already present (CI cache / local re-runs).
set -euo pipefail

VERSION="${COOLIFY_PROVIDER_VERSION:-1.1.20-beskid}"
OS="${RUNNER_OS:-$(uname -s)}"
ARCH="${RUNNER_ARCH:-$(uname -m)}"

_os="$(printf '%s' "${OS}" | tr '[:upper:]' '[:lower:]')"
_arch="$(printf '%s' "${ARCH}" | tr '[:upper:]' '[:lower:]')"
case "${_os}:${_arch}" in
  linux:x64 | linux:amd64) platform="linux_amd64" ;;
  linux:arm64 | linux:aarch64) platform="linux_arm64" ;;
  darwin:x64 | darwin:amd64 | macos:x64 | macos:amd64) platform="darwin_amd64" ;;
  darwin:arm64 | darwin:aarch64 | macos:arm64 | macos:aarch64) platform="darwin_arm64" ;;
  *)
    echo "Unsupported platform: ${OS}/${ARCH}" >&2
    exit 1
    ;;
esac

plugin_root="${HOME}/.terraform.d/plugins/registry.terraform.io/arcusis/coolify/${VERSION}/${platform}"
binary="${plugin_root}/terraform-provider-coolify_v${VERSION}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
src="${repo_root}/beskid_infra/vendor/terraform-provider-coolify"
if [[ ! -f "${src}/go.mod" ]]; then
  echo "Missing vendored provider: ${src} (see beskid_infra/vendor/terraform-provider-coolify/VENDOR.md)" >&2
  exit 1
fi

mkdir -p "${plugin_root}"

if [[ -x "${binary}" && "${FORCE_COOLIFY_PROVIDER_BUILD:-}" != "1" ]]; then
  echo "Coolify provider ${VERSION} (${platform}) already at ${binary} (FORCE_COOLIFY_PROVIDER_BUILD=1 to rebuild)"
else
  echo "Building Coolify provider ${VERSION} (${platform}) from ${src}..."
  cd "${src}"
  export CGO_ENABLED=0
  go build -trimpath -buildvcs=false -ldflags="-s -w" -o "${binary}" .
fi

tofurc="${repo_root}/beskid_infra/terraform.tofurc.generated"
cat > "${tofurc}" <<EOF
# Generated by scripts/ci/install-coolify-provider.sh — do not edit.
provider_installation {
  filesystem_mirror {
    path    = "${HOME}/.terraform.d/plugins"
    include = ["registry.terraform.io/arcusis/coolify"]
  }
  direct {
    exclude = ["registry.terraform.io/arcusis/coolify"]
  }
}
EOF

echo "Wrote ${tofurc}"
