name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-beskid-service
        with:
          service-name: platform-spec
          docker-context: site/platform-spec
          push-image: ${{ github.ref == 'refs/heads/main' }}
          tags: latest
